### ISSUE TITLE
On fail, create comment

### ISSUE THREAD

**Issue by bryantbiggs** [MorrisonCole/pr-lint-action#119]
Great action btw! It would be nice to have the ability to create just a comment as opposed to requesting changes since requesting changes will block workflows (potentially). We want to nudge users to follow a certain PR title but it is not applicable in 100% of the scenarios (say JIRA ticket pattern in the title for example). So in those 1% of the cases, we'd like the action still to nudge them but not block entirely. Anyways, food for thought!

**Comment by MorrisonCole** [comment]
Done courtesy of @bryantbiggs with #121 🎉

**Comment by MorrisonCole** [comment]
@bryantbiggs - just released this with https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.4.0! 

I changed the flag name a little so if you were using your branch while you were waiting, please be aware of that! 🙏
