### ISSUE TITLE
Error when trying to dismiss already dismissed review

### ISSUE THREAD

**Issue by ui-valts-mazurs** [MorrisonCole/pr-lint-action#155]
GitHub API call ends with an error when trying to dismiss a review: `Can not dismiss a dismissed pull request review`. It happens when the action is run for already corrected title.
Seems like `dismissReview` should filter out reviews in `state: DISMISSED`.

**Comment by MorrisonCole** [comment]
Hey @ui-valts-mazurs, thanks for reporting that! 

Sorry had a crazy two weeks so have been a little slow on this - makes sense and planning to fix this up over the weekend.

**Comment by amclay** [comment]
We are also running into this bug, I think possibly when re-running the action when the 1st run hasn't completed

**Comment by MorrisonCole** [comment]
Gotcha - sorry for the delay folks! Still planning to do this shortly 🙏

**Comment by ui-valts-mazurs** [comment]
FYI: there is an error "Can not dismiss a commented pull request review" when the GitHub action was run multiple times for an incorrect title.

**Comment by MorrisonCole** [comment]
Hey @ui-valts-mazurs, @amclay (+ any other watchers). So sorry for my slowness on this one, had a busy time recently and this project became more popular than I expected 😅🐌 

Thanks to @ui-valts-mazurs this has been fixed and released in [v1.4.2](https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.4.2). I tested it out on a [PR here](https://github.com/MorrisonCole/pr-lint-action/pull/164) and all seems to be good. Going forward I'll probably be adding some tests and better contribution documentation - thanks for bearing with me!
