### ISSUE TITLE
Customize the success message when lint succeeds

### ISSUE THREAD

**Issue by dexterastin** [MorrisonCole/pr-lint-action#175]
Hi, I want to customize the success message when lint succeeds (like `✅ Done! All good!`). What do you think? If you don't mind, I'll update the code and create PR.

**Comment by MorrisonCole** [comment]
Hey @dexterastin, apologies for my sloooow response - started a new job and got a bit behind! 😄 

It's a great idea and I'd love it if you still had time to submit that PR, if not I'll get around to it eventually 🙏
