### ISSUE TITLE
Success message does not appear

### ISSUE THREAD

**Issue by talboren** [MorrisonCole/pr-lint-action#266]
For some reason, after a failed comment and when the PR name is fixed, success comment does not appear.
It is very hard to identify where's the problem so I'd like to add some debugging, opening a PR right now.

**Comment by MorrisonCole** [comment]
Thanks for the PR @talboren! I'll get a release out with this shortly so that you don't have to pin to main :)

**Comment by MorrisonCole** [comment]
OK, [v1.6.1](https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.6.1) is released and contains the fix. Thanks again!

**Comment by talboren** [comment]
@MorrisonCole with pleasure! thank you!
