### ISSUE TITLE
default error message add a "." add the end of the regex

### ISSUE THREAD

**Issue by raphaelauv** [MorrisonCole/pr-lint-action#333]
If my regex is 

```yaml
        with:
          title-regex: ^(\[[[A-Z0-9-]+\])+ [\w &.-]+$
```

the error msg is going to be

```
PR title failed to match ^([[[A-Z]+])+ [\w &.-]+$.
```

**Comment by MorrisonCole** [comment]
Thanks for reporting this - agree that it was misleading! Fixed in https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.7.0 :)
