### ISSUE TITLE
Error in 1.7.1 : Error: HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by frottke** [MorrisonCole/pr-lint-action#774]
I'm getting this error after updating 1.7.0 to 1.7.1
`Error: HttpError: Resource not accessible by integration`

context: running in an github workflow with ubuntu-latest.

log with debugging activated below. Thank you very much for looking into the issue :)

```
Run morrisoncole/pr-lint-action@v1.7.1
  with:
    repo-token: ***
    title-regex: \[[A-Za-z]+-[0-9]+\]
    on-failed-regex-fail-action: true
    on-failed-regex-create-review: true
    on-failed-regex-request-changes: true
    on-failed-regex-comment: example text
    on-succeeded-regex-dismiss-review-comment: example text
##[debug]Title Regex: \[[A-Za-z]+-[0-9]+\]
##[debug]Title: Add PR Checks workflow
##[debug]getting reviews
Error: HttpError: Resource not accessible by integration
##[debug]Node Action run completed with exit code 1
```

**Comment by frottke** [comment]
I found the in my own github workflow. I was calling the workflow that uses pr-lint-action by "workflow_call". I had the grant the proper permissions to the workflow. Works now.

**Comment by yermulnik** [comment]
> I had the grant the proper permissions to the workflow. Works now.

@frottke Could you please share which permissions this requires to be granted?
