### ISSUE TITLE
repo-token not defined in action inputs

### ISSUE THREAD

**Issue by negebauer** [MorrisonCole/pr-lint-action#90]
Got the following warning in a workflow

<img width="951" alt="image" src="https://user-images.githubusercontent.com/11860880/90049949-8e18ee80-dca3-11ea-91e1-8fd939e6c1f2.png">

The input is being used
https://github.com/MorrisonCole/pr-lint-action/blob/ea629c5cdd3e3952db64ddc45d86e869c92300d2/src/main.ts#L8

But is not defined in the action file
https://github.com/MorrisonCole/pr-lint-action/blob/ea629c5cdd3e3952db64ddc45d86e869c92300d2/action.yml#L7-L17

**Comment by MorrisonCole** [comment]
Released in https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.2.1 👍
