### ISSUE TITLE
TypeError with v1.2.1

### ISSUE THREAD

**Issue by negebauer** [MorrisonCole/pr-lint-action#92]
Got the following error when running the action

`##[error]TypeError: github_1.GitHub is not a constructor`

**Comment by MorrisonCole** [comment]
Sorry about that, messed up and forgot to rebuild since the releases are somewhat manual at the moment 😅. Fixed now and will shortly release v1.2.2.

**Comment by negebauer** [comment]
It happens haha, waiting on v1.2.2

**Comment by MorrisonCole** [comment]
@negebauer [v1.2.2](https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.2.2) should be good - it just ran on this example PR (https://github.com/MorrisonCole/pr-lint-action/pull/93) :)

**Comment by negebauer** [comment]
Working ! Thanks
